### ISSUE TITLE
Bug After Completing Specific WQ & Question

### ISSUE THREAD

**Issue by NeuroticPixels** [ultijlam/loss-of-control#2]
Completed the world quest Ley Race in Azsuna (https://www.wowhead.com/quest=43325/ley-race) and received this error upon completion:

**1x LossOfControl\Messages.lua:190: bad argument #5 to 'format' (string expected, got nil)
[C]: ?
LossOfControl\Messages.lua:190: in function `CreateLossMessage'
LossOfControl\Core.lua:290: in function `PlayerControlLost'
LossOfControl\Core.lua:303: in function `?'
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
Ace3\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>**

Also, I noticed while doing Timewalking... In Mogu'shan Palace, Haiyan the Unstoppable's "Conflagrate" spell doesn't create a Loss of Control alert. It disoriented my character for a few seconds, I lost control.
Can/will this be added in the future? I also noticed a spell that was put on my character while I was doing a PvE island expedition that caused me to lose control, but the addon didn't notify. Should I make note of spells that aren't caught by the addon and let you know?

**Comment by johnnylam88** [comment]
I will fix the first issue with the nil argument to format in the next release.

For your second question about uncaught spells, "disorient" effects are considered "confused" by the game.  "Confuse" is in the default list of events caught for both tanks and healers.  I've noticed some dungeon mobs can cast abilities that cause loss of control, but don't trigger a Loss Of Control event from the WoW servers.  You can turn on debugging with `/loc debug` when entering a fight where you want to check for events that are not recognized.  If you can report them to me (separate issues are fine), I will see about adding a framework to recognize those spells as well.

**Comment by NeuroticPixels** [comment]
How do you want the reports done? I know separate issues are fine, but any idea what a proper debug message will be? I got this after a boss fight (Xin the Weaponmaster) in Mogu'shan Palace:
**[19:05:34] Loss Of Control: UpdateUnit DRUID DRUID Daraladora Daraladora EmeraldDream EmeraldDream party2 party1 Player-3675-0842CB0F Player-162-09F51D45
[19:05:34] Loss Of Control: UpdateUnit PALADIN PALADIN Lunakat Lunakat nil nil party3 party2 Player-162-09F51D45 Player-60-0B68CBD6
[19:05:35] Loss Of Control: UpdateUnit nil HUNTER nil Brecklyn nil nil nil party1 Player-162-09F51D45 Player-60-0B51A9A4**
Is this any kind of information you can use? Do you need to know the mobs name, what dungeon, etc? And is the debug info it gave any help at all? Doesn't seem like it to me. lol.

**Comment by johnnylam88** [comment]
I've made a new release 1.1.4 that filters the debugging output down to something a bit more useful for you.  The debug level is set to 1 by default for just showing unknown loss of control events.
