### ISSUE TITLE
Utgarde Keep

### ISSUE THREAD

**Issue by ghost** [ultijlam/loss-of-control#3]
I like the addon, but I am not gonna report for every Dungeon this addon has not implemented.

**Comment by johnnylam88** [comment]
The way that Blizzard failed to implement their Loss Of Control system properly to catch all instances of Stuns, Roots, etc., is problematic, but I expect it will improve over time.  For now, I am just trying to catch debuffs that Blizzard has missed and include them into my addon.  However, it takes player data to help me to investigate the dungeons that my low-level toons are not yet able to enter.  I thank you for reporting for Utgarde Keep.
