### ISSUE TITLE
Weird output in chatlog

### ISSUE THREAD

**Issue by ghost** [ultijlam/loss-of-control#4]
In the Dungeon The Mechanar right before the last boss, Pathaleon the Calculator, I got this in my chatlog:

"Loss Of Control: <name> is Polymorphed for 8 seconds: 
[Hex] Loss Of Control: <name> is LOSS_OF_CONTROL_DISPLAY_NONE for 8 seconds
<name> is Polymorphed for 8 seconds.
<name> is LOSS_OF_CONTROL_DISPLAY_NONE for 8 seconds."

<name> is just something I replaced to hide my charname.

**Comment by johnnylam88** [comment]
I hadn't seen how Hex behaved, but I think it causes two different Loss Of Control events, one which is visible (Polymorph) and another effect that is used internally by the game and shouldn't be displayed to the user (LOSS_OF_CONTROL_DISPLAY_NONE).  I've modified the addon to ignore all events that the game hides from the user.  Thanks very much for this interesting bug report.
